name: Deploy to Koyeb

on:
  workflow_run:
    workflows: ["Build", "Continuous Integration (CI)", "Java CI with Gradle", "Scorecard supply-chain security"]
    types:
      - completed

jobs:
  deploy:
    if: >
      ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Koyeb
        run: |
          curl -X POST "https://app.koyeb.com/v1/apps/udehnih/deploy" \
          -H "Authorization: Bearer ${{ secrets.KOYEB_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{"git":{"branch":"main"}}'
