#TODO: CONFIGURE THE DEPLOYMENT
#name: Deploy to Koyeb via CLI
#
#on:
#  workflow_run:
#    workflows: ["Build", "Continuous Integration (CI)", "Java CI with Gradle", "Scorecard supply-chain security"]
#    types:
#      - completed
#
#jobs:
#  deploy:
#    if: ${{ github.event.workflow_run.conclusion == 'success' }}
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v3
#
#      - name: Install Koyeb CLI
#        run: |
#          curl -fsSL https://cli.koyeb.com/install.sh | sh
#          sudo mv /tmp/koyeb /usr/local/bin/koyeb
#
#      - name: Login to Koyeb
#        run: koyeb login --token ${{ secrets.KOYEB_API_TOKEN }}
#
#      - name: Deploy to Koyeb
#        run: |
#          koyeb service redeploy udehnih/udehnih