name: Deploy to Koyeb via CLI

on:
  workflow_run:
    workflows: ["Build", "Continuous Integration (CI)", "Java CI with Gradle", "Scorecard supply-chain security"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Koyeb CLI
        run: |
          echo "Installing Koyeb CLI..."
          # Download the CLI directly from Koyeb's official install script
          curl -sSL https://www.koyeb.com/install.sh | sudo bash
          # Verify installation
          koyeb --version || { echo "Failed to install Koyeb CLI"; exit 1; }

      - name: Authenticate and redeploy Koyeb service
        run: |
          echo "Redeploying service on Koyeb..."
          koyeb service redeploy udehnih-a18 --app udehnih --token ${{ secrets.KOYEB_API_TOKEN }} || { echo "Deployment failed"; exit 1; }
          echo "Deployment triggered successfully!"