name: Deploy to Koyeb via CLI

on:
  workflow_run:
    workflows: ["Build", "Continuous Integration (CI)", "Java CI with Gradle", "Scorecard supply-chain security"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Koyeb CLI
        run: |
          echo "Installing Koyeb CLI..."
          # Download the CLI directly from Koyeb's official install script
          curl -sSL https://www.koyeb.com/install.sh | bash
          # Add to PATH for current session
          export PATH="$HOME/.koyeb/bin:$PATH"
          # Verify installation with full path
          $HOME/.koyeb/bin/koyeb --version || { echo "Failed to verify Koyeb CLI"; exit 1; }
          echo "Koyeb CLI installed successfully"

      - name: Authenticate and redeploy Koyeb service
        run: |
          echo "Redeploying service on Koyeb..."
          # Add to PATH again for this step
          export PATH="$HOME/.koyeb/bin:$PATH"
          $HOME/.koyeb/bin/koyeb service redeploy udehnih-a18 --app udehnih --token ${{ secrets.KOYEB_API_TOKEN }} || { echo "Deployment failed"; exit 1; }
          echo "Deployment triggered successfully!"