name: Deploy to Koyeb via CLI

on:
  workflow_run:
    workflows: ["Build", "Continuous Integration (CI)", "Java CI with Gradle", "Scorecard supply-chain security"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Koyeb CLI
        run: |
          curl -fsSL https://cli.koyeb.com/install.sh | bash
          sudo mv koyeb /usr/local/bin/koyeb

      - name: Authenticate with Koyeb CLI
        run: |
          koyeb auth login --api-token ${{ secrets.KOYEB_API_TOKEN }}

      - name: Deploy to Koyeb
        run: |
          koyeb apps deploy --app udehnih --wait

      - name: Clean up
        run: |
          # Any cleanup steps (optional)
