name: Deploy to Koyeb via CLI

on:
  workflow_run:
    workflows: ["Build", "Continuous Integration (CI)", "Java CI with Gradle", "Scorecard supply-chain security"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Koyeb CLI (if not exists)
        run: |
          if ! command -v koyeb &> /dev/null; then
            echo "Koyeb CLI not found. Installing..."
            curl -sL https://raw.githubusercontent.com/koyeb/koyeb-cli/main/install.sh | bash
          else
            echo "Koyeb CLI already installed."
          fi

      - name: Redeploy Koyeb service
        run: |
          koyeb service redeploy udehnih-a18 --app udehnih --token ${{ secrets.KOYEB_API_TOKEN }}
